use directories::BaseDirs;
use gtk::gdk;
use gtk::glib;
use relm4::adw;
use relm4::adw::prelude::*;
use relm4::prelude::*;

use crate::services::commands::run_command_blocking;
use crate::services::config::AppConfig;

pub struct GesturenModel {
    aktiv: bool,
}

#[derive(Debug)]
pub enum GesturenMsg {
    GestenUmschalten(bool),
}

#[derive(Debug)]
pub enum GesturenCommandOutput {
    Fehler(String),
}

const GESTURE_IMG: &[u8] = include_bytes!("../../../assets/img/gesture.png");

const GESTEN_KONFIG: &str = "\
# libinput-gestures config (generated by Zenbook Control Center)
gesture swipe left 3 xdotool key super+Right
gesture swipe right 3 xdotool key super+Left
gesture swipe up 3 xdotool key super+Up
gesture swipe down 3 xdotool key super+Down
";

#[relm4::component(pub)]
impl Component for GesturenModel {
    type Init = ();
    type Input = GesturenMsg;
    type Output = String;
    type CommandOutput = GesturenCommandOutput;

    view! {
        adw::PreferencesGroup {
            set_title: "Intelligente Gesten",
            set_description: Some("Greifen Sie schnell auf häufig verwendete Einstellungen und Apps zu."),

            add = &gtk::Box {
                set_orientation: gtk::Orientation::Horizontal,
                set_spacing: 24,

                #[name = "gesten_bild"]
                append = &gtk::Picture {
                    set_width_request: 300,
                    set_valign: gtk::Align::Start,
                },

                append = &gtk::ListBox {
                    set_hexpand: true,
                    set_valign: gtk::Align::Start,
                    add_css_class: "boxed-list",

                    append = &adw::SwitchRow {
                        set_title: "Erweiterte Gesten aktivieren/deaktivieren",

                        #[watch]
                        set_active: model.aktiv,

                        connect_active_notify[sender] => move |s| {
                            sender.input(GesturenMsg::GestenUmschalten(s.is_active()));
                        },
                    },

                    append = &adw::ActionRow {
                        set_title: "Lautstärke einstellen",
                        set_subtitle: "Streichen Sie mit einem Finger am linken Rand entlang.",
                    },

                    append = &adw::ActionRow {
                        set_title: "Helligkeit einstellen",
                        set_subtitle: "Streichen Sie mit einem Finger am rechten Rand entlang.",
                    },

                    append = &adw::ActionRow {
                        set_title: "Vor-/Zurückspulen",
                        set_subtitle: "Streichen Sie mit einem Finger über den oberen Rand.",
                    },
                },
            },
        }
    }

    fn init(
        _init: Self::Init,
        _root: Self::Root,
        sender: ComponentSender<Self>,
    ) -> ComponentParts<Self> {
        let aktiv = AppConfig::load().input_gesten_aktiv;
        let model = GesturenModel { aktiv };
        let widgets = view_output!();

        let bytes = glib::Bytes::from_static(GESTURE_IMG);
        if let Ok(texture) = gdk::Texture::from_bytes(&bytes) {
            widgets.gesten_bild.set_paintable(Some(&texture));
        }

        ComponentParts { model, widgets }
    }

    fn update(&mut self, msg: GesturenMsg, sender: ComponentSender<Self>, _root: &Self::Root) {
        match msg {
            GesturenMsg::GestenUmschalten(aktiv) => {
                if aktiv == self.aktiv {
                    return;
                }
                self.aktiv = aktiv;

                AppConfig::update(|c| c.input_gesten_aktiv = aktiv);

                sender.command(move |out, shutdown| {
                    shutdown
                        .register(async move {
                            if aktiv {
                                let konfig_pfad = BaseDirs::new()
                                    .map(|d| d.config_dir().join("libinput-gestures.conf"));

                                if let Some(pfad) = konfig_pfad
                                    && let Err(e) = tokio::fs::write(&pfad, GESTEN_KONFIG).await
                                {
                                    out.emit(GesturenCommandOutput::Fehler(format!(
                                        "libinput-gestures.conf schreiben fehlgeschlagen: {e}"
                                    )));
                                    return;
                                }
                            }

                            let arg = if aktiv { "restart" } else { "stop" };
                            if let Err(e) =
                                run_command_blocking("libinput-gestures-setup", &[arg]).await
                            {
                                out.emit(GesturenCommandOutput::Fehler(e));
                            }
                        })
                        .drop_on_shutdown()
                });
            }
        }
    }

    fn update_cmd(
        &mut self,
        msg: GesturenCommandOutput,
        sender: ComponentSender<Self>,
        _root: &Self::Root,
    ) {
        match msg {
            GesturenCommandOutput::Fehler(e) => {
                let _ = sender.output(e);
            }
        }
    }
}
